minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=100]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: '08cbc46b6e135adec84911b20e98e5bc52032152'
    hooks:
    -   id: mypy
        additional_dependencies: ['types-requests']

  - repo: local
    hooks:
    - id: pytest-check
      name: pytest-check
      entry: poetry run pytest -v ./tests
      language: system
      pass_filenames: false
      always_run: true
